# Generated by Django 5.1.1 on 2024-10-12 18:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_author',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('authorid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('author_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blogid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('blog_image', models.ImageField(upload_to='')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('month', models.CharField(choices=[('farvardin', 'فروردین'), ('ordibehesht', 'اردیبهشت'), ('khordad', 'خرداد'), ('tir', 'تیر'), ('mordad', 'مرداد'), ('shahrivar', 'شهریور'), ('mehr', 'مهر'), ('aban', 'آبان'), ('azar', 'آذر'), ('dey', 'دی'), ('bahman', 'بهمن'), ('esfand', 'اسفند')], max_length=50)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_author')),
            ],
        ),
    ]
