# Generated by Django 5.1.1 on 2024-10-13 11:44

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='month',
            field=models.CharField(choices=[('فروردین', 'farvardin'), ('اردیبهشت', 'ordibehesht'), ('خرداد', 'khordad'), ('تیر', 'tir'), ('مرداد', 'mordad'), ('شهریور', 'shahrivar'), ('مهر', 'mehr'), ('آبان', 'aban'), ('آذر', 'azar'), ('دی', 'dey'), ('بهمن', 'bahman'), ('اسفند', 'esfand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
