# Generated by Django 5.1.1 on 2024-10-13 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_view_count_alter_blog_month_alter_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_review',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('reviewid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review_text', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
