# Generated by Django 5.1.1 on 2024-10-14 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_review_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
