# Generated by Django 5.1.1 on 2024-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_rate_blog_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.CharField(choices=[('آموزش خرید و فروش طلا', 'آموزش خرید و فروش طلا'), ('سرمایه گذاری با طلا', 'سرمایه گذاری با طلا'), ('بورس و بازار جهانی', 'بورس و بازار جهانی'), ('دانستنی طلا', 'دانستنی طلا'), ('سکه طلا', 'سکه طلا')], default='دانستنی طلا', max_length=50),
        ),
    ]
