# Generated by Django 5.1.1 on 2024-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='golzaaar.webp', upload_to=''),
        ),
    ]
