# Generated by Django 5.1.1 on 2024-11-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
