# Generated by Django 5.1.1 on 2024-11-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
